agent: 'kme'
domain: 'walker'
task: 'run_sparse'

n_timesteps: 5000000
checkpoints: []
n_envs: 16
rollout_size: 16384

learning_rate: 0.05
reward_scaling: 1
hidden_dim: 1024
rep_dim: 512
k: 300
balancing_strength: 0.0001
fn_type: 'power'
power_fn_exponent: 0.5
coupled: False
re3_version: 2
re3_granularity: 6666

seed: 666
device: ${oc.env:DEVICE}
    
verbose: 1

exp: ${now:%Y.%m.%d}

hydra:
  run:
    dir: ./outputs/${exp}/${domain}_${task}/${agent}/${now:%H%M%S}
